source 'http://rubygems.org'
ruby '1.9.3'
gem 'sinatra'
gem 'haml'
gem 'activesupport'
gem 'i18n'
gem 'sk_api_schema' #, :git => 'https://github.com/salesking/sk_api_schema.git', :branch => 'master'
gem 'sinatra-partial'
